# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-08 20:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='event',
        ),
        migrations.AddField(
            model_name='events',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cal.Organization'),
            preserve_default=False,
        ),
    ]
